### ISSUE TITLE
[ISSUE] Unresponsive Webpage

### ISSUE THREAD

**Issue by mrepol742** [OshekharO/Webvium-Search#1]
![image](https://user-images.githubusercontent.com/62317165/155099100-757e0831-8f6b-4b52-85f4-3fdcf3b6e1cd.png)

![image](https://user-images.githubusercontent.com/62317165/155099129-c0a8473e-1a4a-48ab-8fbf-340a291938ca.png)

The screenshots shows when the soft keyboard is visible the content of your webpage are still fixed and doesn't move up.

Please fixed this before 12:00AM Central Time.

**Comment by OshekharO** [comment]
Done. Code is under 2kb. ☺️ Sorry was busy studying for my exams.

**Comment by mrepol742** [comment]
Hi OsherkharO,

Dont worry bro.... You're webpage may not be visible in currently release but it is on dev side.. I will rollout another release on the next which includes yours..

Goodluck for your exams, hope you get higher scores..

Regards.
Melvin Jones Repol
